builds:
-
  # environment
  env:
    - CGO_ENABLED=0

  # program
  main: ./cmd/mata/mata.go

  # binary name
  binary: mata

  # which binaries to build
  goos:
    - darwin
    - linux
    - windows

  # which CPU architectures to build
  goarch:
    - amd64

archive:

  format: binary

  files:
    - none*

  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
