// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// DieIf provides a mock function with given fields: err
func (_m *Logger) DieIf(err error) {
	_m.Called(err)
}

// SetLevelTo provides a mock function with given fields: level
func (_m *Logger) SetLevelTo(level string) {
	_m.Called(level)
}

// WriteAt provides a mock function with given fields: level, message, additionalInfo
func (_m *Logger) WriteAt(level string, message string, additionalInfo ...string) {
	_va := make([]interface{}, len(additionalInfo))
	for _i := range additionalInfo {
		_va[_i] = additionalInfo[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, level, message)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// WriteIf provides a mock function with given fields: err, level
func (_m *Logger) WriteIf(err error, level string) {
	_m.Called(err, level)
}
